# Generated by Django 3.1 on 2020-08-19 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_studentextend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentextend',
            name='section',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('To be Filled', 'To be Filled if student')], default='To be Filled if student', max_length=60),
        ),
    ]
